services:
  - type: worker
    name: yuklauz7-bot
    runtime: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    autoDeploy: true
